name: typography
version: 0.0.1
main: docs/index.js
author: Victor Nystad
scripts:
  dev: parcel src/index.html
  build: parcel build src/index.html -d docs
devDependencies:
  autoprefixer: ^9.5.1
  cssnano: ^4.1.10
  parcel-bundler: ^1.12.3
  postcss-cli: ^6.1.2
  postcss-nested: ^4.1.2
